---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-laundromat
rules:
  - apiGroups:
      - extensions
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list"]
  - apiGroups:
      - ""
    resources:
      - pods
    verbs: ["get", "list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-laundromat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-laundromat
subjects:
- kind: ServiceAccount
  name: kubernetes-laundromat
  namespace: default